### ISSUE TITLE
oracle case sensitive column name

### ISSUE THREAD

**Issue by kidzen** [mootensai/yii2-relation-trait#30]
currently

`foreach ($link as $key => $value) {
if (isset($this->$value)) {
                                $array[$key] = "$key = '{$this->$value}'";
                            }
                        }`

suggestion

`foreach ($link as $key => $value) {
                            if (isset($this->$value)) {
                                $array[$key] = "\"$key\" = '{$this->$value}'";
                            }
                        }`

**Comment by mootensai** [comment]
Could you create a pull request please? I agree..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: kidzenSent: Kamis, 23 Februari 2017 16.36To: mootensai/yii2-relation-traitReply To: mootensai/yii2-relation-traitCc: SubscribedSubject: [mootensai/yii2-relation-trait] oracle case sensitive column name (#30)currently
foreach ($link as $key => $value) { if (isset($this->$value)) { $array[$key] = "$key = '{$this->$value}'"; } }
suggestion
foreach ($link as $key => $value) { if (isset($this->$value)) { $array[$key] = "\"$key\" = '{$this->$value}'"; } }

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mootensai/yii2-relation-trait","title":"mootensai/yii2-relation-trait","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mootensai/yii2-relation-trait"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"oracle case sensitive column name (#30)"}],"action":{"name":"View Issue","url":"https://github.com/mootensai/yii2-relation-trait/issues/30"}}}

**Comment by mootensai** [comment]
Thank you!!

**Comment by mootensai** [comment]
could oracle use `` (backtick)?

this code makes duplicate row on mySQL.
see here
https://github.com/mootensai/yii2-enhanced-gii/issues/106
