### ISSUE TITLE
Doesn't work with one to one relationships

### ISSUE THREAD

**Issue by drew1two** [mootensai/yii2-relation-trait#4]
Hi,
RelationTrait seems to assume all method calls to a relationship have an s on the end.  Not the case in hasOne relationships. ie: User / Profile.

**Comment by mootensai** [comment]
Hi! could you give me an sql for example?

**Comment by markux** [comment]
I've a create form with one hasOne related model and the problem is on RelationTrait line 30:

$isHasMany = is_array($value);

ie : On hasOne relation I've POST with User = ['username' => 'markux', 'email' => 'my@email.com'] then $isHasMany became true.

I fixed checking is $value is array of array:

$isHasMany = is_array($value) && is_array(current($value)); // line 30
$relObj->load($value, ''); // line 68 , because without '' it doesn't load from $value
$relPKAttr = is_array($records) ? $records[0]->primaryKey() : $records->primaryKey(); // line 95 because $records it's an object

I hope it help you

thanks

**Comment by mootensai** [comment]
Thank you! 
Could you make a pull request?

**Comment by mootensai** [comment]
Please update..
